name: "Package and Deploy Question Populator to S3"

on:
  push:
    tags:
      - "@couple-game/question-populator-v*"

jobs:
  deploy-s3:
    runs-on: ubuntu-latest
    outputs:
      s3_key: ${{ steps.s3.outputs.s3_key }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Package and Deploy to S3
        id: s3
        uses: ./.github/template/s3
        with:
          app_path_name: question-populator
          package_name: "@couple-game/question-populator"
          s3_bucket_name: ${{ secrets.AWS_LAMBDA_REPOSITORY_BUCKET_NAME }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}

  deploy-lambda:
    runs-on: ubuntu-latest
    needs: deploy-s3
    environment:
      name: "production"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Deploy to Lambda
        uses: ./.github/template/lambda
        with:
          lambda_function_name: question-populator
          s3_bucket_name: ${{ secrets.AWS_LAMBDA_REPOSITORY_BUCKET_NAME }}
          s3_key: ${{ needs.deploy-s3.outputs.s3_key }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          lambda_environment_variables: OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }},OPENAI_PROMPT=${{ secrets.OPENAI_PROMPT }},DYNAMODB_TABLE_NAME=${{ secrets.DYNAMODB_TABLE_NAME }}
