name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      # - name: Setup Node.js 16.x
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 16.x

      # - name: Install pnpm
      #   uses: pnpm/action-setup@v2
      #   with:
      #     version: 8.6.5
      #     run_install: false

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Check Version Changes and Create GitHub Releases
        id: release
        if: steps.changesets.outputs.hasChangesets == 'false'
        uses: ./.github/template/release
        with:
          token: ${{ secrets.PAT }}
