name: "Release Question Refresher to Lambda"

on:
  push:
    tags:
      - "@couple-game/question-refresher-v*"

jobs:
  deploy-s3:
    runs-on: ubuntu-latest
    outputs:
      s3_key: ${{ steps.s3.outputs.s3_key }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Package and Upload to S3
        id: s3
        uses: ./.github/template/s3
        with:
          app_path_name: question-refresher
          package_name: "@couple-game/question-refresher"
          s3_bucket_name: ${{ secrets.AWS_LAMBDA_REPOSITORY_BUCKET_NAME }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}

  deploy-lambda:
    runs-on: ubuntu-latest
    needs: deploy-s3
    environment:
      name: "production"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Deploy to Lambda
        uses: ./.github/template/lambda
        with:
          lambda_function_name: question-refresher
          s3_bucket_name: ${{ secrets.AWS_LAMBDA_REPOSITORY_BUCKET_NAME }}
          s3_key: ${{ needs.deploy-s3.outputs.s3_key }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          lambda_environment_variables: AWS_DYNAMODB_TABLE_NAME=${{ secrets.AWS_DYNAMODB_TABLE_NAME }},AWS_S3_QUESTIONS_BUCKET_NAME=${{ secrets.AWS_S3_QUESTIONS_BUCKET_NAME }}
